{
	"language": "shell",
	"os": "linux",
	"dist": "bionic",
	"arch": "amd64",
	"before_install": "sudo apt-get -y install multistrap dpkg-dev make",
	"script": "make",
	"deploy": {
		"provider": "releases",
		"file": "cogitron.tar.bz2"
	},
}
